server:
  port: 8101
spring:
  data:
    redis:
      host: 192.168.2.102
      port: 6379
      password: 123456
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 123456
    url: jdbc:mysql://192.168.2.102:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.102:8848
    sentinel:
      transport:
        dashboard: localhost:8080
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
feign:
  sentinel:
    enabled: true